name: Matrix Practice
on: push

jobs:
 say-hello:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    number: [1,2,3]
  sreps:
   - name: Print number
     run: echo "this is run number ${{ matrix.number }}"